name: Access to tool and frontend
description: Get access to the tool and front end at https://model-metadata-uploader-dev.apps.live.cloud-platform.service.justice.gov.uk/
body:
  - type: input
    id: name
    attributes:
      label: Name
      description: "What is your name"
      placeholder: "Joe Bloggs"
    validations:
      required: true  
  - type: input
    id: email
    attributes:
      label: Email
      description: "What is your email"
      placeholder: "joe.bloggs@justice.gov.uk"
    validations:
      required: true
